// Importing necessary modules
require('dotenv').config(); // Load environment variables from .env file
const fs = require('fs'); // File system module
const path = require('path'); // Path module for handling file paths

// Access Twilio credentials from environment variables
const accountSid = process.env.TWILIO_ACCOUNT_SID; // Twilio Account SID
const authToken = process.env.TWILIO_AUTH_TOKEN; // Twilio Auth Token

// Import Twilio module and initialize Twilio client
const client = require('twilio')(accountSid, authToken);

/**
 * Function to send an SMS message using Twilio
 * @param {string} body - The message body to be sent via SMS
 */
const sendSMS = async (body) => {
    // Construct message options
    let msgOptions = {
        from: process.env.TWILIO_PHONE_NUMBER, // Sender's phone number from Twilio
        to: process.env.TO_NUMBER, // Receiver's phone number
        body // Message body
    };
    try {
        // Send SMS message using Twilio client
        const message = await client.messages.create(msgOptions);
        console.log(message); // Log the message object upon successful sending
    } catch (error) {
        console.error(error); // Log any errors that occur during sending
    }
};

// Example usage of sendSMS function with a predefined message
sendSMS('Hello from Hrushikesh, Hey Suresh This is Autogenerated message from Twilio');
